# Generated by Django 3.2.8 on 2022-06-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Produto')),
                ('preco_unitario', models.FloatField(max_length=8)),
                ('estoque', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
