# Generated by Django 3.2.8 on 2022-06-14 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220613_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 13, 21, 47, 43, 635785), null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(),
        ),
    ]
