# Generated by Django 3.2.8 on 2022-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20220614_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imgs', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.FloatField(max_length=8, verbose_name='Preço unitário'),
        ),
    ]
