# Generated by Django 3.2.8 on 2022-06-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220614_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço unitário'),
        ),
    ]
