# Generated by Django 3.2.8 on 2022-06-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20220615_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='imgs', verbose_name='Imagem'),
        ),
    ]
