# Generated by Django 3.2.8 on 2022-06-17 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Cliente')),
                ('email', models.EmailField(max_length=120, verbose_name='E-mail')),
                ('endereco', models.TextField(max_length=300, verbose_name='Endereço')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('cpf', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999999)], verbose_name='CPF sem espaços')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Produto'),
        ),
    ]
