# Generated by Django 3.2.8 on 2022-06-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20220617_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor total'),
        ),
    ]
